from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from .views import (
    UserLoginView,
    UserLogoutView,
    address_create,
    address_delete,
    address_set_default,
    address_update,
    api_address_detail,
    api_addresses,
    api_cart,
    api_cart_item,
    add_to_wishlist,
    api_dashboard,
    api_login,
    api_order_detail,
    api_orders,
    api_profile,
    api_register,
    api_wishlist,
    api_wishlist_detail,
    dashboard,
    move_wishlist_to_cart,
    register_view,
    remove_from_wishlist,
    wishlist_view,
)

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', register_view, name='register'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.txt',
        subject_template_name='accounts/password_reset_subject.txt',
        success_url=reverse_lazy('accounts:password_reset_done'),
    ), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/password_reset_done.html',
    ), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html',
        success_url=reverse_lazy('accounts:password_reset_complete'),
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html',
    ), name='password_reset_complete'),
    path('dashboard/', dashboard, name='dashboard'),
    path('addresses/add/', address_create, name='address_create'),
    path('addresses/<int:address_id>/edit/', address_update, name='address_update'),
    path('addresses/<int:address_id>/delete/', address_delete, name='address_delete'),
    path('addresses/<int:address_id>/default/', address_set_default, name='address_set_default'),
    path('wishlist/', wishlist_view, name='wishlist'),
    path('wishlist/add/<slug:slug>/', add_to_wishlist, name='add_to_wishlist'),
    path('wishlist/remove/<slug:slug>/', remove_from_wishlist, name='remove_from_wishlist'),
    path('wishlist/move-to-cart/<slug:slug>/', move_wishlist_to_cart, name='move_wishlist_to_cart'),
    path('api/auth/register/', api_register, name='api_register'),
    path('api/auth/login/', api_login, name='api_login'),
    path('api/profile/', api_profile, name='api_profile'),
    path('api/addresses/', api_addresses, name='api_addresses'),
    path('api/addresses/<int:address_id>/', api_address_detail, name='api_address_detail'),
    path('api/orders/', api_orders, name='api_orders'),
    path('api/orders/<str:order_number>/', api_order_detail, name='api_order_detail'),
    path('api/wishlist/', api_wishlist, name='api_wishlist'),
    path('api/wishlist/<int:product_id>/', api_wishlist_detail, name='api_wishlist_detail'),
    path('api/cart/', api_cart, name='api_cart'),
    path('api/cart/<int:product_id>/', api_cart_item, name='api_cart_item'),
    path('api/dashboard/', api_dashboard, name='api_dashboard'),
]
