# Generated by Django 5.1.7 on 2026-04-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(default='#', max_length=255)),
                ('group', models.CharField(choices=[('company', 'Company'), ('customer', 'Customer'), ('help', 'Help')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('cta_text', models.CharField(default='Shop Now', max_length=40)),
                ('cta_url', models.CharField(default='/shop/', max_length=255)),
                ('accent_label', models.CharField(blank=True, help_text='Example: Up to 38% Off', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('bg_color', models.CharField(default='#eef6ff', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NavItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('url', models.CharField(default='#', max_length=255)),
                ('location', models.CharField(choices=[('primary', 'Primary'), ('category', 'Category')], default='primary', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=120)),
                ('url', models.CharField(default='/shop/', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('color', models.CharField(default='#f0f7ff', max_length=20)),
                ('group', models.CharField(default='hero_right', help_text='hero_right, gadget, unlimited', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['group', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Zynvo', max_length=100)),
                ('tagline', models.CharField(default='Smart living, curated beautifully.', max_length=150)),
                ('support_phone', models.CharField(default='+880 1700-000000', max_length=30)),
                ('support_email', models.EmailField(default='support@zynvo.com', max_length=254)),
                ('address', models.CharField(default='Dhaka, Bangladesh', max_length=255)),
                ('copyright_text', models.CharField(default='© 2026 Zynvo Ltd. All Rights Reserved', max_length=255)),
                ('hero_title', models.CharField(default='Elevate your everyday with Zynvo', max_length=140)),
                ('hero_subtitle', models.CharField(default='Discover hand-picked lifestyle, fashion, and gadget essentials with fast delivery.', max_length=255)),
                ('announcement_text', models.CharField(default='Free shipping on orders over ৳3000', max_length=255)),
                ('corporate_cta_title', models.CharField(default='Become Our Corporate Partner', max_length=140)),
                ('corporate_cta_url', models.CharField(default='/corporate/', max_length=255)),
                ('facebook_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaticPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('body', models.TextField()),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('excerpt', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blogcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
