# Generated by Django 6.0.4 on 2026-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroslide',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='promobanner',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
    ]
