# Generated by Django 5.1.7 on 2026-04-05 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('specifications', models.TextField(blank=True)),
                ('return_policy', models.TextField(blank=True, default='7 days replacement available for damaged or defective items.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('compare_at_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('brand', models.CharField(default='Zynvo', max_length=80)),
                ('badge_text', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_daily_deal', models.BooleanField(default=False)),
                ('is_trending', models.BooleanField(default=False)),
                ('collection_label', models.CharField(blank=True, max_length=80)),
                ('trending_group', models.CharField(blank=True, default='General', max_length=80)),
                ('deal_ends_at', models.DateTimeField(blank=True, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=140)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalog.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(default='Color', max_length=50)),
                ('value', models.CharField(max_length=80)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('sku', models.CharField(blank=True, max_length=60)),
                ('price_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/variants/')),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
            ],
            options={
                'unique_together': {('product', 'attribute_name', 'value')},
            },
        ),
    ]
