# Generated by Django 6.0.4 on 2026-04-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_ean_productfaq_productreview_stockalert'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='external_image_url',
            field=models.URLField(blank=True),
        ),
    ]
